--CREATE USER yada PASSWORD 'yada';
--ALTER USER yada SET SEARCH_PATH to yada;
--CREATE DATABASE yada OWNER=yada;

--GRANT ALL PRIVILEGES ON DATABASE yada TO yada WITH GRANT OPTION;
--GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA yada TO yada;

--\connect yada yada
--CREATE SCHEMA yada AUTHORIZATION yada;

SET SEARCH_PATH to yada;

DROP TABLE IF EXISTS YADA_TEST;
CREATE TABLE IF NOT EXISTS YADA_TEST
(
	COL1 VARCHAR(3),
	COL2 INT,
	COL3 DECIMAL(2,1),
	COL4 DATE,
	COL5 TIMESTAMP,
	userid VARCHAR(320) DEFAULT ''
);

-- YADA_UG is a whitelist table for the yada-admin webapp
DROP TABLE IF EXISTS YADA_USER;
CREATE TABLE YADA_USER
(
  USERID VARCHAR(255) NOT NULL,
  PW  VARCHAR(20) NOT NULL
);

-- YADA_UG is a whitelist table for the yada-admin webapp
DROP TABLE IF EXISTS YADA_UG;
CREATE TABLE IF NOT EXISTS YADA_UG
(
  APP VARCHAR(20) NOT NULL,
  USERID VARCHAR(255) NOT NULL,
  ROLE VARCHAR(20) NOT NULL
);
