<template>
  <li class="list-group-item" :data-app="app" @click="loadApp">{{app}}</li>
</template>

<script>
  export default {
    name: 'AppListItem',
    props: ['app'],
    methods: {
      // executes yada queries on click to load configuration and queries for display
      loadApp (e) {
        // the queries to execute and the events to emit on response
        let queries = [{qname:'YADA select app config',event:'config-loaded.app'},
                       {qname:'YADA queries',event:'queries-loaded.app'}]
        // build the jsonparams
        let j = []
        queries.forEach(function(q){
          j.push({qname:q.qname,DATA:[{APP:e.target.dataset.app}]})
        })
        // exec the queries
        this.$yada.jp(j).then(resp => this.handleMultiResp(resp,queries))
      },
      // handles the multiquery response generated by 'loadApp'
      //TODO this might belong in a mixin
      handleMultiResp (resp,queries) {
        let that = this
        // iterate over the queries to emit the corresponding events and
        // pass the correct response (RESULTSET) object in its payload
        queries.forEach(function(q){
          let obj = that._(resp.data.RESULTSETS)
                        .map(function(o) {return o.RESULTSET})
                        .filter({qname:q.qname}).value()
          that.$emit(q.event,obj)
        })
      }
    }
  }
</script>

<style scoped>

</style>
