<template>
  <a class="list-group-item list-group-item-action"
      :id="app"
      href="#"
      role="tab"
      :data-app="app"
      @click="loadApp"
      data-toggle="list">{{app}}</a>
</template>

<script>
  export default {
    name: 'AppListItem',
    props: ['app'],
    data () {
      return {

      }
    },
    methods: {

      // executes yada queries on click to load configuration and queries for display
      loadApp (e) {

        // the queries to execute and the events to emit on response
        let queries = ['YADA select app config','YADA queries']

        // build the jsonparams
        let j = []
        queries.forEach(function(q){
          j.push({qname:q,DATA:[{APP:e.target.dataset.app}]})
        })
        // exec the queries
        this.$yada.jp(j).then(resp => this.handleMultiResp(resp,queries))
      },

      // handles the multiquery response generated by 'loadApp'
      //TODO this might belong in a mixin
      handleMultiResp (resp,queries) {
        let that = this
        // iterate over the queries to emit the corresponding events and
        // pass the correct response (RESULTSET) object in its payload
        queries.forEach(function(q){
          let evt = q.replace(/\s/g,'-') + '.loaded.app'
          let obj = resp.data.RESULTSETS.map(o => o.RESULTSET).filter(o => o.qname == q)
          that.$emit(evt,obj)
        })
      }
    }
  }
</script>

<style scoped>

</style>
